### ISSUE TITLE
Cannot open keytar.node

### ISSUE THREAD

**Issue by guoyangyang666** [thundernet8/StarCabinet#13]
Hello, I use the MacBook development environment, but the program started to report wrong, if you have time please help me to solve it, thank you.
![1111111](https://user-images.githubusercontent.com/22006863/35429111-8dc5ddb2-02ad-11e8-86aa-f423229d6d37.png)

**Comment by thundernet8** [comment]
do you tried 'npm rebuild'? 


发送自我的三星盖乐世智能手机。
-------- 原始信息 --------由： guoyangyang666 <notifications@github.com> 日期: 2018/1/26  15:29  (GMT+08:00) 收件人： thundernet8/StarCabinet <StarCabinet@noreply.github.com> 抄送： Subscribed <subscribed@noreply.github.com> 主题： [thundernet8/StarCabinet] Cannot open keytar.node (#13) 
Hello, I use the MacBook development environment, but the program started to report wrong, if you have time please help me to solve it, thank you.



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thundernet8/StarCabinet","title":"thundernet8/StarCabinet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/thundernet8/StarCabinet"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Cannot open keytar.node (#13)"}],"action":{"name":"View Issue","url":"https://github.com/thundernet8/StarCabinet/issues/13"}}}

**Comment by thundernet8** [comment]
please pull the lastest code v2.0, your problem can be resolved by running commond `npm run rebuild`
